# Generated by Django 3.2.5 on 2021-07-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obyekt',
            options={'verbose_name': 'Kitob', 'verbose_name_plural': 'Kitoblar'},
        ),
    ]
