# Generated by Django 3.2.5 on 2021-07-30 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libnews', '0002_alter_obyekt_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Kategoriya nomi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='obyekt',
            name='bolim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='libnews.bolim'),
        ),
    ]
