# Generated by Django 3.2.5 on 2021-08-13 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libnews', '0003_auto_20210731_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obyekt',
            name='bolim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='libnews.bolim'),
            preserve_default=False,
        ),
    ]
